version: '3.8'

services:
  # Database
  postgres:
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: qualgen
      POSTGRES_USER: qualgen
      POSTGRES_PASSWORD: qualgen123
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./docker/postgres/init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U qualgen"]
      interval: 30s
      timeout: 10s
      retries: 5

  # Redis
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 30s
      timeout: 10s
      retries: 5

  # Job Server
  job-server:
    build:
      context: .
      dockerfile: Dockerfile.server
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: development
      PORT: 3000
      HOST: 0.0.0.0
      DATABASE_URL: postgresql://qualgen:qualgen123@postgres:5432/qualgen
      REDIS_URL: redis://redis:6379
      LOG_LEVEL: info
      MAX_CONCURRENT_JOBS: 10
      JOB_TIMEOUT_MS: 300000
      RETRY_ATTEMPTS: 3
      AGENT_HEARTBEAT_INTERVAL: 30000
      AGENT_TIMEOUT_MS: 60000
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/api/health"]
      interval: 30s
      timeout: 10s
      retries: 5

  # QualGen Job Orchestrator
  job-orchestrator:
    build:
      context: .
      dockerfile: Dockerfile.orchestrator
    ports:
      - "8080:8080"  # REST API
      - "50051:50051"  # gRPC
    environment:
      NODE_ENV: production
      PORT: 8080
      GRPC_PORT: 50051
      DATABASE_URL: postgresql://qualgen:qualgen123@postgres:5432/qualgen
      REDIS_URL: redis://redis:6379
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  # QualGen Dashboard
  dashboard:
    build:
      context: .
      dockerfile: Dockerfile.dashboard
    ports:
      - "3007:3007"
    environment:
      NODE_ENV: production
      API_URL: http://job-orchestrator:8080
    depends_on:
      - job-orchestrator
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3007/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  # Example Test Agent (Emulator)
  test-agent-emulator:
    build:
      context: .
      dockerfile: Dockerfile.agent
    environment:
      QGJOB_SERVER_URL: http://job-server:3000
      AGENT_NAME: emulator-agent-1
      AGENT_CAPABILITIES: '[{"target": "emulator", "platform": "android", "version": "11"}]'
      MAX_CONCURRENT_JOBS: 2
    depends_on:
      job-server:
        condition: service_healthy

  # Example Test Agent (Device)
  test-agent-device:
    build:
      context: .
      dockerfile: Dockerfile.agent
    environment:
      QGJOB_SERVER_URL: http://job-server:3000
      AGENT_NAME: device-agent-1
      AGENT_CAPABILITIES: '[{"target": "device", "platform": "android", "device_name": "Pixel_5"}]'
      MAX_CONCURRENT_JOBS: 1
    depends_on:
      job-server:
        condition: service_healthy

volumes:
  postgres_data:
  redis_data:

networks:
  default:
    name: qualgen-network
